### ISSUE TITLE
Add better error handling on HTTP 500

### ISSUE THREAD

**Issue by fproulx-eoscanada** [eoscanada/eosc#109]
HTTP 500 errors are not displayed well

on the wire
```
Internal Server Error
Content-Length: 409
Content-Type: application/json
Date: Fri, 23 Nov 2018 21:22:14 GMT
Server: WebSocket++/0.7.0
Via: 1.1 google
Connection: close

{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: overdrawn balance","file":"wasm_interface.cpp","line_number":934,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":72,"method":"exec_one"}]}}
```

in the console:
`ERROR: pushing transaction: Internal Service Error`

**Comment by DenisCarriere** [comment]
👍 Bumping this issue

Not having good error handling is very hard to troubleshoot errors, most of the time it's lack of CPU, but only but receiving `ERROR: pushing transaction: Internal Service Error` is not useful.

Could `.error.details[0].message` be the error message and fallback to `.message` (Internal Service Error)

**Comment by abourget** [comment]
yes, this was fixed (it displays the idented JSON) in latest.. I'm going to do a release.

**Comment by abourget** [comment]
Released in https://github.com/eoscanada/eosc/releases/tag/v1.2.0
