### ISSUE TITLE
Render `get account` better than a JSON output.

### ISSUE THREAD

**Issue by abourget** [eoscanada/eosc#12]

**Comment by tampajohn** [comment]
@abourget open for help on this?  I'd think for a non-verbose printing, we could present the account data that is available on eostoolkit:

EOS ####.####    RAM #### unit used #### unit owned    
CPU ####.#### EOS (###.##% used)    NET ####.#### EOS (###.##% used)    REFUNDING ####.#### EOS

(optional)
TOKENS ####.#### EOS, ####.#### {TOKEN} ...

**Comment by abourget** [comment]
The most precise output for that is `cleos`'s.. if you want to implement something like that, it'd be great. Permissions in hierarchy, all the types of permissions on a line, with their weights..
the right format for units (the rounding on `cleos` is solid too, with significant number of decimals)... proper differences for staked and delegated bandwidths.

We could keep the --json output for refs and precision (precise rather than rounded numbers).

What do you think?

**Comment by tampajohn** [comment]
Sounds like the right idea, I will replicate what cleos pops out.

I think keeping the json makes sense, and if we want to support output
other formats (yaml?) later on that will be easy enough

**Comment by tampajohn** [comment]
@abourget Going to leverage columnize since that's already in the project, you were the one that added it so I'm assuming you're happy with it :)

**Comment by joshkauffman** [comment]
These are all just noted differences between the new output and what the json shows, not necessarily all important

-not noted if it's a privileged account or not
-doesn't display `last_code_update` (not sure when that is valuable though?
-does not display `created` timestamp
-displays things like RAM, and Net in KiB/MiB whereas most explorers use KB and MB (even eosquery does - so we're displaying two different things)
-doesn't display if there is a current refund request
-doesn't show any proxy info (whether it's regd as one, or if it's proxying to one)
-doesn't show vote weight (which I'd really like to see :slightly_smiling_face: )

**Comment by tampajohn** [comment]
@joshkauffman Thanks for the delta list... I agree that some things are missing/should be there, I just tried to replicate the formatting and information found in cleos.  @abourget I can add some of these items to #18 if it makes sense?

**Comment by tampajohn** [comment]
@joshkauffman regarding the KiB vs KB, both KiB and KB are 1024 bytes, versus kB being 1000 bytes.  Looking at eosquery I'm seeing that they use KB, which means we should be displaying the same numbers.  Are you seeing discrepancies?
