### ISSUE TITLE
Allow for `linkauth` to link to contract::wildcard

### ISSUE THREAD

**Issue by joshkauffman** [eoscanada/eosc#123]
Currently returns an error of: `ERROR: invalid name format for "action name": empty` when trying to link `linkauth` a contract without defining a specific action (as in: `eosc system linkauth msigexample2 eosforumrcpp "" all`)

Will then need to decide on how we will display this in eosq. Currently it displays as:
`contract@` and that's it. (One account that has a wildcard linkauth is `mryeateshere` if you need to take a look)

**Comment by abourget** [comment]
Fixed by fa0427a8
