### ISSUE TITLE
Feature Request: Pass transaction by string

### ISSUE THREAD

**Issue by eosinbox** [eoscanada/eosc#126]
It would be nice to be able to pass a transaction by string (similar to what cleos supports) instead of filename. This would allow tools such as EOS Inbox to allow a user to copy the full eosc tx sign command with a transaction string.

**Comment by maoueh** [comment]
Sure, that would be great. Can you show me how it looks like when used through `cleos`?

**Comment by eosinbox** [comment]
Here is an example of the voteproducer action:

cleos --url https://mainnet.eos.dfuse.io push transaction '{
  "expiration": "2019-04-19T00:22:13.000",
  "ref_block_num": 15058,
  "ref_block_prefix": 1731519432,
  "max_net_usage_words": 0,
  "max_cpu_usage_ms": 0,
  "delay_sec": 0,
  "context_free_actions": [],
  "actions": [
    {
      "account": "eosio",
      "name": "voteproducer",
      "authorization": [
        {
          "actor": "eosinboxdapp",
          "permission": "active"
        }
      ],
      "data": {
        "voter": "eosinboxdapp",
        "proxy": "brockpierce1",
        "producers": []
      }
    }
  ],
  "transaction_extensions": []
}'

**Comment by maoueh** [comment]
Perfect, thanks. We are looking into it.
