### ISSUE TITLE
Add support to unlock vault by command line parameter

### ISSUE THREAD

**Issue by kthamm** [eoscanada/eosc#128]
I would like to use eosc to automatically deploy contracts with GitLab CI.
That means I would like to be able to pass the passphrase as a command line parameter.

Is there a option to do this already that I am missing?

**Comment by maoueh** [comment]
You can use environment variable `EOSC_GLOBAL_INSECURE_VAULT_PASSPHRASE` to hold the passphrase of the vault.

Note also that most command line parameter can be defined via environment variable by using the prefix `EOSC_GLOBAL` like: `EOSC_GLOBAL_API_URL`, `EOSC_GLOBAL_VAULT_FILE`, etc.

**Comment by kthamm** [comment]
Thank you!

**Comment by fproulx-eoscanada** [comment]
@kthamm we chose to use an environment variable as you can load it without leaving traces in . bash history, you can have a bash . script do:
```
EOSC_GLOBAL_INSECURE_VAULT_PASSPHRASE=$(cat mypassphrase.txt) eosc vault serve...
```

**Comment by kthamm** [comment]
Hi,
while this works when I use it on a local machine, it fails when I try to execute it with Gitlab CI in a docker container:
`EOSC_GLOBAL_INSECURE_VAULT_PASSPHRASE=$(cat passphrase.txt) eosc system setcontract ...`
`Enter passphrase to decrypt your vault:`
`ERROR: setting up wallet: secret boxer: reading password: inappropriate ioctl for device`

Any ideas?

**Comment by maoueh** [comment]
The password is ask if the value is not set or if it's the empty string. So this could print if `$(cat passphrase.txt)` is not doing anything.

Be also sure to have a recent enough version of `eosc`, this was added in `v.1.1.0`.

You could try to `export` first and then run the command, I really doubt it would make a difference but could be.

You can check the actual value as it would be seen within the `eosc` process:

```
EOSC_GLOBAL_INSECURE_VAULT_PASSPHRASE=$(cat passphrase.txt) bash -c 'echo "$EOSC_GLOBAL_INSECURE_VAULT_PASSPHRASE"'
```

**Comment by kthamm** [comment]
Yeah sorry I was stupid. It works now :) Thank you for your help!

**Comment by maoueh** [comment]
@kthamm Excellent :)

**Comment by str** [comment]
What if the passphrase IS an empty string?

**Comment by maoueh** [comment]
@str Normally, I assume it should work. If it doesn't, please open a new issue so we can take a look.

**Comment by str** [comment]
It didn't.   I tried:

EOSC_GLOBAL_INSECURE_VAULT_PASSPHRASE= ./eosc
EOSC_GLOBAL_INSECURE_VAULT_PASSPHRASE="" ./eosc

Ad without setting anything, and it kept asking for the  password.  I'm about to open a new issue then.
