### ISSUE TITLE
Enforce `weight` attribute to be included in authority JSON when performing `updateauth` action

### ISSUE THREAD

**Issue by DenisCarriere** [eoscanada/eosc#132]
I've recently been able to pushed a `system updateauth` action when the JSON authority file was missing the `weight` attribute, this caused the account to "null" out the permission since the authority had a weight of 0.

If `weight` is `undefined` eosc should raise an error instead of pushing `updateauth` with a weight of 0 as the default.

**Should raise an error (missing `weight`)**
```json
{
  "threshold": 1,
  "keys": [
    {
      "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"
    }
  ]
}
```

**Valide authority JSON**
```json
{
  "threshold": 1,
  "keys": [
    {
      "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
      "weight": 1
    }
  ]
}
```

**Comment by abourget** [comment]
Ouch. This needs fixing. I thought `nodeos` checked for those risks.. surprised it accepts a weight of 0.. what's the use of a weight of 0 otherwise?!

**Comment by abourget** [comment]
Do you have a link to your transaction?

**Comment by DenisCarriere** [comment]
@abourget 

I've created a new transaction with the following authority

https://kylin.eosq.app/tx/69a61fc2465820b98eae51d354878e8233ac2fc38a50aef8faebde94c5a81c60

```json
{
    "threshold": 1,
    "keys": [
        {
            "key": "EOS74F5gi5wFQzSCo5mQ2p8ihERFw3RWARwMnXoyQ88fQQU1hXxCp",
            "weight": 0
        },
        {
            "key": "EOS7jUe6kEXz93RMeYpze33ek1uyNSegGf4CCDQWSU4DTh9N6kjEC",
            "weight": 1
        },
        {
            "key": "EOS8ZSQhzNqYn5nNnLARJzUMSwv1stbMNMPxHcsQ9W4SoztZ5mZ6K"
        }
    ],
    "accounts": [
        {
            "permission": {
                "actor": "deniscarrier",
                "permission": "active"
            },
            "weight": 1
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/550895/57731726-528b1100-7669-11e9-9f6e-243998660b3e.png)

I did test if you only provide 1 public key with threshold of 1, the system does throw an error (so that's good).

**Does throw an error**

```json
{
    "threshold": 1,
    "keys": [
        {
            "key": "EOS8ZSQhzNqYn5nNnLARJzUMSwv1stbMNMPxHcsQ9W4SoztZ5mZ6K"
        }
    ],
    "accounts": []
}
```
> ERROR: pushing transaction: Internal Service Error: Action validate exception: Invalid authority: {"threshold":1,"keys":[{"key":"EOS8ZSQhzNqYn5nNnLARJzUMSwv1stbMNMPxHcsQ9W4SoztZ5mZ6K","weight":0}],"accounts":[],"waits":[]}: pending console output:

**Comment by maoueh** [comment]
Should be resolved now.

**Comment by DenisCarriere** [comment]
🎉
