### ISSUE TITLE
REX support for no-EOS core symbol

### ISSUE THREAD

**Issue by DenisCarriere** [eoscanada/eosc#136]
The `eosc rex` feature does not work for networks such as BOS that doesn't use `EOS` symbol.

```bash
$ eosc -u https://bos.eosn.io rex deposit <ACCOUNT> "1.0000 BOS" 
ERROR: invalid 4,EOS asset for "quantity": EOS has max 4 decimals
```

**Comment by DenisCarriere** [comment]
Woohoo 🎉

**Comment by maoueh** [comment]
Note that by being on the right chain, it will infer the core symbol automatically. So:

```
eosc -u https://bos.eosn.io rex deposit <ACCOUNT> 1
```

Will now work as expected, normally.

**Comment by DenisCarriere** [comment]
👍 yea, that's expected

Looking forward to check out this improvements
