### ISSUE TITLE
Better support for other chains

### ISSUE THREAD

**Issue by joshkauffman** [eoscanada/eosc#143]
Speaking with one of the guys from Worbli today and he mentioned he had an issue when trying to create a new account using eosc.
His report: 
Todor - worbli.io, [Jul 3, 2019 at 12:20:44 PM]:
Usage:
  eosc system newaccount [creator] [new_account_name] [flags]

Flags:
      --auth-file string     File containing owner and active permissions authorities. See example in --help
      --auth-key string      Public key to use for both owner and active permissions.
      --buy-ram string       The amount of EOS to spend to buy RAM for the new account (at current EOS/RAM market price)

the part about —buy-ram - I couldn't get it to accept another symbol

well actually I got around that using —buy-ram-kbytes but then I couldn't get —stake-cpu and —stake-net to work

By my look, it doesn't look like just adding a --contract flag would solve this. Need to see if it's forcing the symbol/contract, and how to add a flag to overcome this

**Comment by maoueh** [comment]
Try latest version @joshkauffman, the one in `master` branch.

Added support for automatic inference of the core symbol based on the actual chain RPC. Was working well with BOS, Worbli should probably works not also out of the box.

Please report.

**Comment by maoueh** [comment]
If you tests are conclusive, I would release a new "official" version.

**Comment by joshkauffman** [comment]
He pulled the new version and it's working now. Issue closed. Will maybe need update the header info to make it more clear though.
