### ISSUE TITLE
WAX blockchain: unsupported protocol scheme "" on every command

### ISSUE THREAD

**Issue by GassaFM** [eoscanada/eosc#147]
I'm trying to use `eosc` with WAX blockchain. But every request fails. The basic example:

```eosc -u chain.wax.io get info```

The result is:

```ERROR: get info: chain.wax.io/v1/chain/get_info: Post chain.wax.io/v1/chain/get_info: unsupported protocol scheme ""```

Other requests fail because `get_info` is not available in the first place.

Still, https://chain.wax.io/v1/chain/get_info opens on the web for me just fine.

Is there an override to try the commands anyway, despite the protocol scheme apparently not being specified?

**Comment by maoueh** [comment]
Hmmm weird this unsupported scheme thing, wondering why such error can happen in a so easy HTTP call. I’ll have a look today and get back to you.

**Comment by sduchesneau** [comment]
The protocol should be http ->
`eosc -u http://chain.wax.io get info` and `eosc -u https://chain.wax.io get info`
gets you the right results.

The help specifies clearly what is being expected of the `-u` flag:
```  -u, --api-url string              API endpoint of eos.io blockchain node (default "https://mainnet.eoscanada.com")```

**Comment by GassaFM** [comment]
Aha, so it's a simple user error. Sorry then, and thanks for looking into it!
