### ISSUE TITLE
I'm not able to skip the password setting an empty password

### ISSUE THREAD

**Issue by str** [eoscanada/eosc#153]
I'm not able to skip the password setting an empty password.   I tried:

```
EOSC_GLOBAL_INSECURE_VAULT_PASSPHRASE= ./eosc
EOSC_GLOBAL_INSECURE_VAULT_PASSPHRASE="" ./eosc
```

and without setting anything, and it kept asking for the  password.  I'm about to open a new issue then.

**Comment by fproulx-dfuse** [comment]
If that env var is empty we consider that you want interactive prompt. If your goal is to automate in a script and not bother with passphrase on the vault. I simply suggest you put a bogus passphrase, like `"passphrase`" or `"insecure"`
