### ISSUE TITLE
Output full data for `get account`

### ISSUE THREAD

**Issue by joshkauffman** [eoscanada/eosc#21]
Here's a list of the items not being displayed by the new version of `get account`
(as noted in #12 )

-not noted if it's a privileged account or not
-doesn't display last_code_update
-does not display created timestamp
-displays things like RAM, and Net in KiB/MiB whereas most explorers use kB and mB (even eosquery does - so we're displaying two different things)
-doesn't display if there is a current refund request
-doesn't show any proxy info (whether it's regd as one, or if it's proxying to one)
-doesn't show vote weight (which I'd really like to see 🙂 )

**Comment by tampajohn** [comment]
These make sense, and I can def add it into the formatted output.  

Regarding the KiB vs kB, I have to be missing something ... looks like eosquery uses KB/MB which is KiB/MiB... where are you seeing otherwise (ie, seeing kB/mB where the bytes are divisible by 1000 instead of 1024).

**Comment by maoueh** [comment]
@joshkauffman When you have time, can you check what is missing from the list in the latest version, so we can update your issue with the latest information required.

**Comment by joshkauffman** [comment]
It seems like none of my notes above have been taken into account. Unless they have been pushed into a specific branch? @maoueh

**Comment by fproulx-eoscanada** [comment]
@tampajohn do you still consider helping for this?
I'm cleaning up issues and gathering them into milestones for post `v1.0.0` release.
I'd like this to go for `v1.1.0` (early October). If you tell me you can take those, I will focus and other features and happily merge your PR - no rush.

Cheers,

**Comment by tampajohn** [comment]
@fproulx-eoscanada, Yes I will carve out time to tackle these, should be able to get it done in the next week.

**Comment by tampajohn** [comment]
I'm going to go ahead and make producers multiline/indented as well... current formatting for lots of producers looks crappy

**Comment by tampajohn** [comment]
@fproulx-eoscanada The changes requested should all be there, if we're good then looking forward to all the 1.1.0 changes! :)
