### ISSUE TITLE
Improvements to vote commands

### ISSUE THREAD

**Issue by maoueh** [eoscanada/eosc#52]
- [ ] in `vote` next to `producers` it reads as "Cast your vote for 1 to 30 producers. View them with 'list'" and should be replaced with "Cast your vote for 1 to 30 producers. View them with 'list-producers'"
- [ ] in `vote` next to `cancel-all` it reads as "Cancel all votes currently casted for producers and reset proxy voting." and should be replaced with "Cancel all votes currently cast for producers/delegated to a proxy"
- [ ] in `vote` next to `proxy` it reads as " Cast your vote for a proxy voter" and should be replaced with "Proxy your vote strength to a proxy"
- [ ]  in `vote` next to `status` remove the period at the end of the description
- [x] within `vote` we need to add functionality to register and unregister as a proxy
- [ ] `vote status` for an account shows its vote strength as "1.8413023710936929e+12" need to reformat this into a number `"last_vote_weight": 1841302371093.6929`

Reported by @joshkauffman at https://github.com/eoscanada/eosc/pull/45#issuecomment-420441657

See #45

**Comment by fproulx-eoscanada** [comment]
Resolved by #56
