### ISSUE TITLE
Unable to run `forum expire`

### ISSUE THREAD

**Issue by joshkauffman** [eoscanada/eosc#96]
Whenever I try to expire a proposal that I have made before it's set expiration time, I receive the error: 
`ERROR: pushing transaction: https://mainnet.eoscanada.com/v1/chain/push_transaction: status code=500, body={"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: proposal not found.","file":"wasm_interface.cpp","line_number":930,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":61,"method":"exec_one"}]}}`

**Comment by abourget** [comment]
I read `proposal not found` in there? Perhaps the proposal is not found?

what was the input ?

**Comment by maoueh** [comment]
So, proposal was indeed not existing?

**Comment by joshkauffman** [comment]
Lol two months old. Not a clue. I probably debugged it and cleaned up the
code to fix it for you guys :P
Tomorrow I will go look thru old issues and close any of mine that may
still be open
